baseurl = "https://penguinpowernz.github.io/"
languageCode = "en-us"
title = "Penguin Power"
Author = "Robert McLeod"
publishDir = "docs"

[permalinks]
  post = "/:year/:month/:title/"

[Params]
subtitle = "Doing awesome stuff with Linux"
highlightjs = "androidstudio"
dateFormat = "02 Jan 2006, 15:04"


[social]
github = "penguinpowernz"
twitter = "penguinpowernz"


[menu]
  [[menu.main]]
      name = "Home"
      pre = "<i class='fa fa-home fa-fw'></i>"
      weight = 0
      identifier = "home"
      url = "/"
